/* LakshyaSetu multilingual test layer — additive only. */
(function(){
  const KEY='ls_test_language', labels={en:'English',te:'తెలుగు',hi:'हिन्दी'};
  const getLang=()=>localStorage.getItem(KEY)||'en';
  const setLang=l=>{localStorage.setItem(KEY,l);window.dispatchEvent(new CustomEvent('ls-language-change',{detail:l}));};
  window.LSLanguage={get:getLang,set:setLang,labels};
  function selector(host){if(!host||host.dataset.lsLangReady)return;host.dataset.lsLangReady='1';const box=document.createElement('div');box.style.cssText='display:flex;align-items:center;gap:7px;flex-wrap:wrap;margin:8px 0';const lab=document.createElement('span');lab.textContent='Language';lab.style.cssText='font-size:12px;font-weight:800;color:#64748b';box.appendChild(lab);const s=document.createElement('select');s.id='lsLanguage';s.style.cssText='padding:7px 9px;border:1px solid #cbd5e1;border-radius:8px;background:#fff;font-weight:700';Object.entries(labels).forEach(([k,v])=>{const o=document.createElement('option');o.value=k;o.textContent=v;s.appendChild(o)});s.value=getLang();s.onchange=()=>setLang(s.value);box.appendChild(s);host.prepend(box)}
  async function getTranslations(lang){try{const db=getLakshyaSetuDb();const r=await db.from('ls_test_question_translations').select('test_question_id,question,option_a,option_b,option_c,option_d,explanation,statements').eq('language',lang);if(r.error)throw r.error;const out={};(r.data||[]).forEach(x=>out[x.test_question_id]=x);return out}catch(e){console.warn('Multilingual layer: English fallback active.',e);return {}}}
  function installStudent(){
    const app=document.getElementById('app'),qbox=document.getElementById('question');if(!app||!qbox)return;
    selector(document.querySelector('.bar')||app);let qs=[],cache={},testId=Number(new URLSearchParams(location.search).get('test')||new URLSearchParams(location.search).get('test_id'));
    const apply=async()=>{const lang=getLang();if(lang==='en')return;const m=(qbox.querySelector('p')?.textContent||'').match(/Question\s+(\d+)\s+of\s+(\d+)/i);if(!m)return;const index=Number(m[1])-1;if(!qs.length){try{const r=await getLakshyaSetuDb().from('ls_test_questions').select('id,question,option_a,option_b,option_c,option_d').eq('test_id',testId).order('display_order',{ascending:true});if(r.error)throw r.error;qs=r.data||[]}catch(e){return}}if(!cache.__lang||cache.__lang!==lang){cache=await getTranslations(lang);cache.__lang=lang}const q=qs[index],tr=q&&cache[q.id];if(!q||!tr)return;const h=qbox.querySelector('h2');if(h)h.textContent=tr.question||q.question;const opts=[...qbox.querySelectorAll('.opt')];['a','b','c','d'].forEach((k,i)=>{const b=opts[i];if(!b)return;const prefix=k.toUpperCase()+'. ';b.textContent=prefix+(tr['option_'+k]||q['option_'+k]||'')});};
    const schedule=()=>setTimeout(apply,80);window.addEventListener('ls-language-change',()=>{cache={};schedule()});new MutationObserver(schedule).observe(qbox,{childList:true,subtree:true});schedule();
  }
  function installStudentHub(){const top=document.querySelector('.top');if(top)selector(top);}
  function installHome(){const nav=document.querySelector('.nav');if(nav)selector(nav)}
  function installAdmin(){const app=document.getElementById('app');if(!app||app.dataset.lsLangAdmin)return;app.dataset.lsLangAdmin='1';const card=document.createElement('div');card.className='card';card.style.marginTop='15px';card.innerHTML='<h2>Translation Setup</h2><p class="muted">English remains the master MCQ. Telugu and Hindi translations are stored separately for new tests, so existing questions, scoring, payments and the current workflow stay unchanged.</p><div class="msg">New-test flow: save English MCQs first; translations are attached to the same question IDs. Student language choice is English / తెలుగు / हिन्दी.</div>';app.appendChild(card)}
  function boot(){if(location.pathname.endsWith('/home.html')||location.pathname==='/'||location.pathname.endsWith('/'))installHome();if(location.pathname.endsWith('/student-test.html'))installStudent();if(location.pathname.endsWith('/student-v2.html'))installStudentHub();if(location.pathname.endsWith('/admin-test-builder.html'))installAdmin()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
