/* LakshyaSetu multilingual test layer — additive only. */
(function(){
  const KEY='ls_test_language', labels={en:'English',te:'తెలుగు',hi:'हिन्दी'};
  const getLang=()=>localStorage.getItem(KEY)||'en';
  const setLang=l=>{localStorage.setItem(KEY,l);window.dispatchEvent(new CustomEvent('ls-language-change',{detail:l}));};
  window.LSLanguage={get:getLang,set:setLang,labels};
  async function getTranslations(lang){try{const db=getLakshyaSetuDb();const r=await db.from('ls_test_question_translations').select('test_question_id,question,option_a,option_b,option_c,option_d,explanation,statements').eq('language',lang);if(r.error)throw r.error;const out={};(r.data||[]).forEach(x=>out[x.test_question_id]=x);return out}catch(e){console.warn('Multilingual layer: translation table unavailable.',e);return {}}}
  async function autoTranslate(text,target){
    text=String(text||''); if(!text||target==='en')return text;
    try{const u='https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl='+encodeURIComponent(target)+'&dt=t&q='+encodeURIComponent(text);const r=await fetch(u);if(!r.ok)throw new Error('translation request failed');const d=await r.json();return Array.isArray(d?.[0])?d[0].map(x=>x?.[0]||'').join(''):text}catch(e){console.warn('Automatic translation fallback:',e);return text}
  }
  window.LSTranslate={translate:autoTranslate};
  function languageButtons(){return '<div style="display:grid;gap:10px;margin-top:18px"><button data-lang="en" style="padding:14px;border:1px solid #cbd5e1;border-radius:10px;background:#fff;text-align:left;font-weight:800;cursor:pointer">🇬🇧 English</button><button data-lang="te" style="padding:14px;border:1px solid #cbd5e1;border-radius:10px;background:#fff;text-align:left;font-weight:800;cursor:pointer">తెలుగు</button><button data-lang="hi" style="padding:14px;border:1px solid #cbd5e1;border-radius:10px;background:#fff;text-align:left;font-weight:800;cursor:pointer">हिन्दी</button></div>';}
  function studentGate(){
    const app=document.getElementById('app'),status=document.getElementById('status');if(!app||!status)return;if(document.getElementById('lsLanguageGate'))return;
    app.classList.add('hidden');status.className='';status.innerHTML='<div id="lsLanguageGate" style="background:#fff;border:1px solid #dbe4ee;border-radius:14px;padding:24px;max-width:680px;margin:10px auto"><h1 style="margin-top:0;color:#173b67">Select Test Language</h1><p style="color:#526174">Choose the language in which you want to attempt this test. Your choice will be used for the questions, options and explanations.</p>'+languageButtons()+'<p id="lsLangMsg" style="font-size:12px;color:#64748b;margin-bottom:0"></p></div>';
    document.querySelectorAll('#lsLanguageGate [data-lang]').forEach(btn=>btn.onclick=()=>{setLang(btn.dataset.lang);status.className='hidden';app.classList.remove('hidden');applyCurrentLanguage()});
  }
  let cache={};
  async function loadTranslationQuestions(testId){try{const r=await getLakshyaSetuDb().from('ls_test_questions').select('id,question,option_a,option_b,option_c,option_d,explanation,statements').eq('test_id',testId).order('display_order',{ascending:true});return r.error?[]:(r.data||[])}catch(e){return []}}
  async function applyLanguageToQuestionBox(qbox,qs){
    if(!qbox||!qs?.length)return;const lang=getLang();if(lang==='en')return;let index=-1;
    const marker=(qbox.querySelector('.qnum')||qbox.querySelector('p'))?.textContent||'';const m=marker.match(/Question\s+(\d+)\s+of\s+(\d+)/i);if(m)index=Number(m[1])-1;
    if(index<0){const text=qbox.querySelector('.question, h2')?.textContent?.trim()||'';index=qs.findIndex(q=>String(q.question||'').trim()===text)};if(index<0)return;
    if(cache.__lang!==lang){cache=await getTranslations(lang);cache.__lang=lang}const q=qs[index],tr=q&&cache[q.id];
    const translateField=async(field)=>{const stored=tr&&String(tr[field]||'').trim();return stored||await autoTranslate(q?.[field]||'',lang)};
    const h=qbox.querySelector('.question')||qbox.querySelector('h2');if(h)h.textContent=await translateField('question');
    const opts=[...qbox.querySelectorAll('.option, .opt')];for(let i=0;i<4;i++){const k=['a','b','c','d'][i],b=opts[i];if(!b)continue;const letter=b.querySelector('.letter')?.textContent?.trim()||k.toUpperCase()+'.';const text=(tr&&String(tr['option_'+k]||'').trim())||await autoTranslate(q['option_'+k]||'',lang);if(b.classList.contains('option'))b.innerHTML='<span class="letter">'+letter+'</span><span>'+text+'</span>';else b.innerHTML='<b>'+k.toUpperCase()+'.</b> '+text}
    const st=qbox.querySelector('.statement');if(st){const text=(tr&&String(tr.statements||'').trim())||await autoTranslate(q.statements||'',lang);if(text)st.innerHTML='<b>Statements / Data</b><br>'+String(text).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]))}
    const ex=qbox.querySelector('.explanation');if(ex){const text=(tr&&String(tr.explanation||'').trim())||await autoTranslate(q.explanation||'',lang);if(text)ex.textContent=text}
  }
  async function applyCurrentLanguage(){const p=new URLSearchParams(location.search),testId=Number(p.get('test')||p.get('test_id')||0),qs=window.__LS_TRANSLATION_QS||(testId?await loadTranslationQuestions(testId):[]);window.__LS_TRANSLATION_QS=qs;const qbox=document.getElementById('question');if(qbox)await applyLanguageToQuestionBox(qbox,qs);const adminQ=document.querySelector('#app .qcard');if(adminQ)await applyLanguageToQuestionBox(adminQ,qs)}
  function adminPreviewGate(){const app=document.getElementById('app');if(!app||document.getElementById('lsAdminLanguageGate')||window.__LS_ADMIN_LANGUAGE_SELECTED)return;if(!/admin-test-preview\.html$/i.test(location.pathname))return;const wrap=document.createElement('div');wrap.id='lsAdminLanguageGate';wrap.style.cssText='position:fixed;inset:0;background:rgba(15,35,63,.55);z-index:9999;display:flex;align-items:center;justify-content:center;padding:20px';wrap.innerHTML='<div style="background:#fff;border:1px solid #dbe4ee;border-radius:16px;padding:28px;max-width:560px;width:100%;box-shadow:0 18px 50px rgba(15,35,63,.22)"><div style="font-size:11px;font-weight:900;color:#2457a6;letter-spacing:.04em">LAKSHYASETU · TEST LANGUAGE</div><h1 style="margin:8px 0;color:#173b67;font-size:25px">Select Test Language</h1><p style="color:#526174;line-height:1.5;margin-bottom:0">Choose the language before beginning this test. Questions, options and explanations use your selection. The Home page does not have a language selector.</p>'+languageButtons()+'<p style="font-size:12px;color:#64748b;margin:14px 0 0">Your selection is used for this test only.</p></div>';document.body.appendChild(wrap);wrap.querySelectorAll('[data-lang]').forEach(btn=>btn.onclick=async()=>{window.__LS_ADMIN_LANGUAGE_SELECTED=true;setLang(btn.dataset.lang);wrap.remove();cache={};await applyCurrentLanguage()})}
  function installStudent(){const app=document.getElementById('app'),qbox=document.getElementById('question');if(!app||!qbox)return;studentGate();const testId=Number(new URLSearchParams(location.search).get('test')||new URLSearchParams(location.search).get('test_id'));const loadQs=async()=>{window.__LS_TRANSLATION_QS=await loadTranslationQuestions(testId)};loadQs();window.addEventListener('ls-language-change',()=>{cache={};setTimeout(applyCurrentLanguage,100)});new MutationObserver(()=>setTimeout(applyCurrentLanguage,50)).observe(qbox,{childList:true,subtree:true})}
  function installStudentHub(){/* Language choice belongs inside a test, not on the home/dashboard. */}
  function installHome(){/* Intentionally no language selector on Home. */}
  function installAdmin(){const app=document.getElementById('app');if(!app||app.dataset.lsLangAdmin)return;app.dataset.lsLangAdmin='1';const card=document.createElement('div');card.className='card';card.style.marginTop='15px';card.innerHTML='<h2>Translation Setup</h2><p class="muted">English remains the master MCQ. Telugu and Hindi translations are stored separately when available; automatic translation is used for existing/future questions and explanations when a stored translation is not present.</p><div class="msg">New-test flow: save English MCQs first; students choose English / తెలుగు / हिन्दी when starting a test.</div>';app.appendChild(card)}
  function installAdminPreview(){adminPreviewGate();const app=document.getElementById('app');if(!app)return;const run=()=>{adminPreviewGate();if(!document.getElementById('lsAdminLanguageGate')&&window.__LS_ADMIN_LANGUAGE_SELECTED)setTimeout(applyCurrentLanguage,50)};new MutationObserver(run).observe(app,{childList:true,subtree:true});window.addEventListener('ls-language-change',()=>{cache={};setTimeout(applyCurrentLanguage,50)})}
  function boot(){if(location.pathname.endsWith('/home.html')||location.pathname==='/'||location.pathname.endsWith('/'))installHome();if(location.pathname.endsWith('/student-test.html'))installStudent();if(location.pathname.endsWith('/student-v2.html'))installStudentHub();if(location.pathname.endsWith('/admin-test-builder.html'))installAdmin();if(location.pathname.endsWith('/admin-test-preview.html'))installAdminPreview()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();