/* LakshyaSetu Razorpay payment client v2 */
(function(){
  if(window.__LS_PAYMENT_V2_ACTIVE)return;
  window.__LS_PAYMENT_V2_ACTIVE=true;
  window.__LS_PAYMENT_MODULE_LOADED=true;
  function db(){return window.getLakshyaSetuDb();}
  async function session(){const c=db();const r=await c.auth.getSession();if(r.data?.session)return r.data.session;const rr=await c.auth.refreshSession();return rr.data?.session||null;}
  async function loadRazorpay(){if(window.Razorpay)return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=resolve;s.onerror=()=>reject(new Error('Payment gateway failed to load.'));document.head.appendChild(s);});}
  async function invoke(name,body){const c=db();let s=await session();if(!s)throw new Error('Authentication failed. Please login again.');let r=await c.functions.invoke(name,{body});if(r.error?.status===401){const rr=await c.auth.refreshSession();s=rr.data?.session||null;if(!s)throw new Error('Authentication failed. Please login again.');r=await c.functions.invoke(name,{body});}if(r.error){let detail='';try{if(r.error.context){const x=await r.error.context.json();detail=x?.error||x?.message||'';}}catch(_e){}throw new Error(detail||r.data?.error||r.error.message||'Payment service failed.');}if(!r.data?.success)throw new Error(r.data?.error||'Payment service failed.');return r.data;}
  async function buy(product,label,knownSession){try{const s=knownSession||await session();if(!s){location.href='login.html?next='+encodeURIComponent(location.href);return;}await loadRazorpay();const orderData=await invoke('create-razorpay-order',product);const user=s.user||{},meta=user.user_metadata||{};const rzp=new Razorpay({key:orderData.key_id,amount:orderData.order.amount,currency:orderData.order.currency||'INR',name:'LakshyaSetu',description:label||product.product_type,order_id:orderData.order.id,prefill:{name:String(meta.full_name||meta.name||''),email:String(user.email||''),contact:String(meta.phone||meta.mobile||'')},method:{card:true,netbanking:true,upi:true,wallet:true,emi:true,paylater:true},retry:{enabled:true,max_count:3},timeout:600,handler:async response=>{try{await invoke('verify-razorpay-payment',{...product,amount:orderData.amount,razorpay_order_id:response.razorpay_order_id,razorpay_payment_id:response.razorpay_payment_id,razorpay_signature:response.razorpay_signature});alert('Payment successful. Access activated.');location.reload();}catch(e){alert(e.message||'Payment verification failed.');}},modal:{ondismiss:()=>console.info('Razorpay checkout dismissed.')}});rzp.on('payment.failed',response=>alert('Payment failed: '+(response?.error?.description||'Please retry.')));rzp.open();}catch(e){alert(e.message||'Payment failed.');}}
  window.LSBuy=buy;window.LSGetSession=session;
})();
